# dbt project configuration for the retail analytics engineering pipeline

name: 'retail_analytics_dbt_snowflake_pipeline'
version: '1.0.0'

# This setting configures which profile dbt uses for this project.
# The same profile name should exist in your local profiles.yml file.
profile: 'retail_analytics_dbt_snowflake_pipeline'

# These configurations specify where dbt should look for different project files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories removed when running: dbt clean
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

# Model configurations
models:
  retail_analytics_dbt_snowflake_pipeline:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

# Seed configurations
seeds:
  retail_analytics_dbt_snowflake_pipeline:
    +quote_columns: false

# Snapshot configurations
snapshots:
  retail_analytics_dbt_snowflake_pipeline:
    +target_schema: snapshots